### ISSUE TITLE
how can i enable travel payout search flight API

### ISSUE THREAD

**Issue by arjun-kava** [Alex7Kom/node-travelpayouts#2]
i had tried out every possible way, i had create whitelabel and also setup CNAME points to fresh.travelpayout.com , but still i'm getting response code 403 and Unauthorized, my account is paid account and there is message displaying "Access is denied", for search API, i can't get proper steps to enable search API

![flight_search](https://cloud.githubusercontent.com/assets/5005729/21100334/8c9dad4a-c099-11e6-807b-9b478a6801e5.png)

**Comment by alex7kom** [comment]
As far as I know you need to send a request to Travelpayouts Support. (See [instructions](https://support.travelpayouts.com/hc/en-us/articles/210995808-Requirements-for-API-access)).
Sorry, can't get you further as I'm not even a Travelpayouts employee.

Also, I'm closing the issue because this is not a Travelpayouts Helpdesk.
